name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and deploy mod1_solution
        run: |
          mkdir -p public/mod1_solution
          cp -r mod1_solution/* public/mod1_solution
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

      - name: Build and deploy mod2_solution
        run: |
          mkdir -p public/mod2_solution
          cp -r mod2_solution/* public/mod2_solution
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public